apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}-aioa
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}-aioa
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.name}}-aioa
  template:
    metadata:
      labels:
        app: {{gitops.name}}-aioa
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          args:
          - --sleep
          - "100"
          - --prometheus
          - --run-loop
          - --verbose
          - --server
          - https://central-tx-austin-101.cseretail.com
          - https://central-tx-austin-102.cseretail.com
          - https://central-mo-kc-101.cseretail.com
          - https://central-mo-kc-102.cseretail.com
          - https://east-nc-raleigh-101.cseretail.com
          - https://east-nc-raleigh-102.cseretail.com
          - https://west-wa-redmond-101.cseretail.com
          - https://west-wa-redmond-102.cseretail.com
          - --files
          - ngsa-benchmark.json
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}
          - --log-format
          - Json
---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-aioa
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}-aioa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}-aioa
