apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}-tlog
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}-tlog
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.name}}-tlog
  template:
    metadata:
      labels:
        app: {{gitops.name}}-tlog
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 2
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          args:
          - --sleep
          - "5000"
          - --prometheus
          - --run-loop
          - --server
          - https://central-tx-austin-101.cseretail.com
          - https://central-tx-austin-102.cseretail.com
          - https://central-mo-kc-101.cseretail.com
          - https://central-mo-kc-102.cseretail.com
          - https://east-ga-atlanta-101.cseretail.com
          - https://east-ga-atlanta-102.cseretail.com
          - https://east-nc-raleigh-101.cseretail.com
          - https://east-nc-raleigh-102.cseretail.com
          - https://west-wa-redmond-102.cseretail.com
#           - https://west-wa-seattle-101.cseretail.com
#           - https://west-wa-seattle-102.cseretail.com
          - https://west-ca-sd-101.cseretail.com
          - https://west-ca-sd-102.cseretail.com
          - --files
          - tlog-benchmark.json
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}
          - --log-format
          - Json
---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-tlog
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}-tlog
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}-tlog
