apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-order-accuracy-beta
  namespace: aioa-beta
  labels:
    app.kubernetes.io/name: ai-order-accuracy-beta
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: ai-order-accuracy-beta
  template:
    metadata:
      labels:
        app: ai-order-accuracy-beta
        deploy: deploy-22-02-28-03-35-58
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/aioa:beta
          imagePullPolicy: Always
          args:
          - --in-memory
          - --prometheus
          - --zone
          - west-wa-redmond
          - --region
          - west
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ai-order-accuracy-beta
  namespace: aioa-beta
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ai-order-accuracy-beta

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ai-order-accuracy-beta-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`west-wa-redmond-102.cseretail.com`)
      kind: Rule
      services:
        - name: ai-order-accuracy-beta
          namespace: aioa-beta
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
