x flux-check /s/v bootstrap\bartr-central\flux-check
x flux-check /s/v bootstrap\bartr-east\flux-check
x flux-check /s/v bootstrap\bartr-west\flux-check
x flux-check /s/v bootstrap\central-mo-kc-101\flux-check
x flux-check /s/v bootstrap\central-mo-kc-102\flux-check
x flux-check /s/v bootstrap\central-tx-austin-101\flux-check
x flux-check /s/v bootstrap\central-tx-austin-102\flux-check
x flux-check /s/v bootstrap\corp-monitoring-101\flux-check
x flux-check /s/v bootstrap\east-ga-atlanta-101\flux-check
x flux-check /s/v bootstrap\east-ga-atlanta-102\flux-check
x flux-check /s/v bootstrap\east-nc-raleigh-101\flux-check
x flux-check /s/v bootstrap\east-nc-raleigh-102\flux-check
x flux-check /s/v bootstrap\west-ca-sd-101\flux-check
x flux-check /s/v bootstrap\west-ca-sd-102\flux-check
x flux-check /s/v bootstrap\west-wa-redmond-101\flux-check
x flux-check /s/v bootstrap\west-wa-redmond-102\flux-check
x flux-check /s/v bootstrap\west-wa-seattle-101\flux-check
x flux-check /s/v bootstrap\west-wa-seattle-102\flux-check
