apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv-ngsa
  namespace: webv
  labels:
    app.kubernetes.io/name: webv-ngsa
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: webv-ngsa
  template:
    metadata:
      labels:
        app: webv-ngsa
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/webvalidate:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          args:
          - --sleep
          - "100"
          - --prometheus
          - --run-loop
          - --server
          - https://central-tx-austin-101.cseretail.com
          - https://central-tx-austin-102.cseretail.com
          - https://central-mo-kc-101.cseretail.com
          - https://central-mo-kc-102.cseretail.com
          - https://east-nc-raleigh-101.cseretail.com
          - https://east-nc-raleigh-102.cseretail.com
          - --files
          - benchmark.json
          - --zone
          - corp-monitoring
          - --region
          - corp
          - --log-format 
          - Json
---
apiVersion: v1
kind: Service
metadata:
  name: webv-ngsa
  namespace: webv
  labels:
    app: webv-ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webv-ngsa
