apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv
  namespace: webv
  labels:
    app.kubernetes.io/name: webv
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: webv
  template:
    metadata:
      labels:
        app: webv
        version: beta-2202-17-13
        deploy: deploy-22-02-17-13-30-21
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/webvalidate:beta
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1000m"
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          args:
          - -l
          - "5000"
          - --prometheus
          - -r
          - -s
          - https://central-tx-austin-101.cseretail.com
          - https://central-tx-austin-102.cseretail.com
          - https://central-mo-kc-101.cseretail.com
          - https://central-mo-kc-102.cseretail.com
          - https://east-ga-atlanta-101.cseretail.com
          - https://east-ga-atlanta-102.cseretail.com
          - https://west-wa-seattle-101.cseretail.com
          - https://west-wa-seattle-102.cseretail.com
          - https://west-ca-sd-101.cseretail.com
          - https://west-ca-sd-102.cseretail.com
          - -u
          - https://raw.githubusercontent.com/retaildevcrews/akdc/main/red-vms/webv/
          - -f
          - benchmark.json
          - --zone
          - corp-monitoring
          - --region
          - corp
          - --log-format 
          - Json
---
apiVersion: v1
kind: Service
metadata:
  name: webv
  namespace: webv
  labels:
    app: webv
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webv
