apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtlog
  namespace: vtlog
  labels:
    app.kubernetes.io/name: vtlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtlog
  template:
    metadata:
      labels:
        app: vtlog
        deployTag: deploy-2022-04-05-19-42-08
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/vtlog:latest
          imagePullPolicy: Always
          args:
          - --region
          - west
          - --zone
          - west-wa-redmond
          - --district
          - west-wa-redmond
          - --store
          - west-wa-redmond-102
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /tlog/readyz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /tlog/healthz
              port: 8080
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: vtlog
  namespace: vtlog
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vtlog

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vtlog-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`west-wa-redmond-102.cseretail.com`) && PathPrefix(`/tlog/`)
      kind: Rule
      services:
        - name: vtlog
          namespace: vtlog
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
