apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-{{gitops.name}}
  namespace: {{gitops.namespace}}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-{{gitops.name}}
  namespace: {{gitops.namespace}}
rules:
- apiGroups: [ "" ]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-{{gitops.name}}
  namespace: {{gitops.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-{{gitops.name}}
subjects:
- kind: ServiceAccount
  name: fluent-bit-{{gitops.name}}
  namespace: {{gitops.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-{{gitops.name}}-config
  namespace: {{gitops.namespace}}
  labels:
    k8s-app: fluent-bit-{{gitops.name}}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf
  output.conf: |
    [OUTPUT]
        Name              kafka
        Match             kube.var.log.containers.vtlog*.*
        brokers                     corp-monitoring-eh.servicebus.windows.net:9093
        topics                      corp-monitoring-eh
        rdkafka.security.protocol   SASL_SSL
        rdkafka.sasl.username       $ConnectionString
        rdkafka.sasl.password       ${EVENT_HUB_CONNECTION_STRING}
        rdkafka.sasl.mechanism      PLAIN
        storage.total_limit_size 15M
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/vtlog*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes
        Add_prefix    kubernetes_
    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes_labels
        Add_prefix    kubernetes_labels_
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep   Off
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit-{{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: fluent-bit-{{gitops.name}}
    deployTag: deploy-2022-04-05-19:42:08
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit-{{gitops.name}}
  template:
    metadata:
      name: fluent-bit-{{gitops.name}}
      labels:
        app.kubernetes.io/name: fluent-bit-{{gitops.name}}
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluent-bit-{{gitops.name}}
      terminationGracePeriodSeconds: 10
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.5
          imagePullPolicy: Always
          env:
          - name: EVENT_HUB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: fluent-bit-vtlog-secret
                key: EventHubConnectionString
          ports:
            - containerPort: 2020
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
          - name: varlog
            mountPath: /var/log

          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true

          - name: fluent-bit-{{gitops.name}}-config
            mountPath: /fluent-bit/etc/

      volumes:
        - name: varlog
          hostPath:
            path: /var/log

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: fluent-bit-{{gitops.name}}-config
          configMap:
            name: fluent-bit-{{gitops.name}}-config
