apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
        deployTag: deploy-2022-04-05-19:42:08
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          args:
          - --region
          - {{gitops.config.region}}
          - --zone
          - {{gitops.config.zone}}
          - --district
          - {{gitops.config.district}}
          - --store
          - {{gitops.config.store}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /tlog/readyz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /tlog/healthz
              port: 8080
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{gitops.name}}-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{gitops.config.domain}}`) && PathPrefix(`/tlog/`)
      kind: Rule
      services:
        - name: {{gitops.name}}
          namespace: {{gitops.namespace}}
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
